---
title: "Sanity Check: Replicating past papers' calculations"
author: "Brandon Waldon"
date: "1/13/2021"
output: html_document
---

```{r setup, results = 'hide'}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
library(grid)
library(gridExtra)
library(cowplot)
library(viridis)
library(jsonlite)
source("../_shared/runwppl_fromweb.R")
engine <- read_file("../_shared/engine.txt")

modelout <- function(cmd, modelAndSemantics, alpha, sizeNoiseVal, colorNoiseVal, 
                     sizeCost, colorCost, nounCost, states, utterances) {
  
  preamble <- sprintf("var params = {
    alpha : %f,
    sizeNoiseVal : %f,
    colorNoiseVal : %f,
    sizeCost : %f,
    colorCost : %f,
    nounCost : %f
    } \n
    var model = extend(model(params), \n {states : %s, utterances : %s}) 
                 ", alpha, sizeNoiseVal, colorNoiseVal, sizeCost, colorCost, nounCost, toJSON(states), toJSON(utterances))
  
  code <- paste(modelAndSemantics, preamble, engine, cmd, sep = "\n")
  write_file(code,"code.txt")
  return(evalWebPPL_V8(code))
  
}
```

# Cohn Gordon et al. Figure 1

```{r CohnGordon}
knitr::opts_chunk$set(echo = TRUE)
cg_utterances <- c("START dress STOP", "START red dress STOP","START red object STOP")
cg_states <- c("R1","R2","R3")
cg_sizeNoise = 1 # NO SIZE NOISE IN THE MODEL (VACUOUS)
cg_colorNoise = 1 # NO COLOR NOISE IN THE MODEL (VAVUOUS)
cg_alpha = 1 
cg_modelAndSemantics = read_file("models/CohnGordonetal/modelAndSemantics.txt")
```

### GLOBAL LITERAL LISTENER

```{r}

L0_UTT_probs <- expand.grid(state = cg_states, utterance = cg_utterances) %>%
  mutate(command = sprintf('Math.exp(globalLiteralListener("%s", model, params, 
                           semantics(params)).score("%s"))',
                           utterance, state))

L0_UTT_probs$probability <- 0

for(i in 1:nrow(L0_UTT_probs)) {
  L0_UTT_probs$probability[i] <- modelout(L0_UTT_probs$command[i],
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances) }

L0_UTT_probs %>% select(state,utterance,probability)
```

### GLOBAL UTTERANCE-LEVEL PREDICTIONS

```{r}

S1_UTT_GP_probs <- expand.grid(state = cg_states, utterance = cg_utterances) %>%
  mutate(command = sprintf('Math.exp(globalUtteranceSpeaker("%s", model, params, 
                           semantics(params)).score("%s"))',
                           state, utterance))

S1_UTT_GP_probs$probability <- 0

for(i in 1:nrow(S1_UTT_GP_probs)) {
  S1_UTT_GP_probs$probability[i] <- modelout(S1_UTT_GP_probs$command[i],
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances) }

S1_UTT_GP_probs %>% select(state,utterance,probability)
```

### INCREMENTAL UTTERANCE-LEVEL PREDICTIONS

```{r}

S1_UTT_IP_probs <- expand.grid(state = cg_states, utterance = cg_utterances) %>%
  mutate(command = sprintf('incrementalUtteranceSpeaker("%s", "%s", model, params, 
                           semantics(params))',
                           utterance, state))

S1_UTT_IP_probs$probability <- 0

for(i in 1:nrow(S1_UTT_IP_probs)) {
  S1_UTT_IP_probs$probability[i] <- modelout(S1_UTT_IP_probs$command[i],
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances) }


S1_UTT_IP_probs %>% select(state, utterance, probability)

```

### INCREMENTAL RSA SPEAKER PREDICTIONS

```{r results="hold"}

print("--- R1 ---")

print("First step:")

modelout('wordSpeaker(["START"], "R1", model, params, 
                           semantics(params))',
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances)
print("Second step:")

modelout('wordSpeaker(["START", "red"], "R1", model, params, 
                           semantics(params))',
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances)

print("--- R2 ---")

print("First step:")

modelout('wordSpeaker(["START"], "R2", model, params, 
                           semantics(params))',
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances)
print("Second step:")

modelout('wordSpeaker(["START", "red"], "R2", model, params, 
                           semantics(params))',
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances)

print("--- R3 ---")

print("First step:")

modelout('wordSpeaker(["START"], "R3", model, params, 
                           semantics(params))',
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances)
print("Second step:")

modelout('wordSpeaker(["START", "red"], "R3", model, params, 
                           semantics(params))',
                                           cg_modelAndSemantics,
                                           cg_alpha, cg_sizeNoise, cg_colorNoise,
                                           0, 0, 0, cg_states, cg_utterances)
```

# Degen et al. (ForestDB simulations)

```{r}
d_utterances <- c("big pin", "small pin", "blue pin", "red pin", "big blue pin", "small blue pin", "big red pin")
d_states <- c("bigblue","bigred","smallblue")
d_sizeNoise = 0.8 
d_colorNoise = 0.99 
d_alpha = 30 
d_modelAndSemantics = read_file("models/Degenetal/modelAndSemantics.txt")
```

### CONTINUOUS-SEMANTICS SPEAKER UTTERANCE PREDICTIONS

```{r}

S1_C_probs <- expand.grid(state = d_states, utterance = d_utterances) %>%
  mutate(command = sprintf('Math.exp(globalUtteranceSpeaker("%s", model, params, 
                           semantics(params)).score("%s"))',
                           state, utterance))

S1_C_probs$probability <- 0

for(i in 1:nrow(S1_C_probs)) {
  S1_C_probs$probability[i] <- modelout(S1_C_probs$command[i],
                                           d_modelAndSemantics,
                                           d_alpha, d_sizeNoise, d_colorNoise,
                                           0, 0, 0, d_states, d_utterances)
}

S1_C_probs %>% filter(state == "smallblue") %>% select(utterance,state,probability)
```
